<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Language strings for AI Video Activity.
 *
 * @package    mod_aivideoactivity
 * @copyright  2025 Essay Grader AI
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// Module info.
$string['modulename'] = 'AI Video Activity';
$string['modulenameplural'] = 'AI Video Activities';
$string['modulename_help'] = 'AI Video Activity attaches a self-marking quiz to video or audio content, with questions generated by AI directly from the media transcript.

Two media modes are supported. YouTube Video mode accepts any YouTube URL and automatically fetches the video transcript. Audio File mode accepts uploaded audio files up to 256 MB (MP3, WAV, OGG, M4A, AAC, FLAC, WMA, OPUS, WebM, AIFF) — suitable for speaking assessments, evacuation siren identification, podcast-based learning, or any spoken audio content.

Questions are generated from the transcript at a configurable Bloom\'s Taxonomy level (Level 1 Remember through Level 6 Create). Nine question types are available: Multiple Choice, True/False, Matching, Ordering, Fill in the Blanks, Short Answer, Scenario-based, Sequencing, and Hotspot. Each answer option includes an AI voiceover explanation generated in the teacher\'s chosen language using Google Chirp 3 HD text-to-speech (52 languages supported).

Three media gate modes control when the quiz unlocks: No requirement (media shown alongside quiz), Watch/listen for a minimum number of seconds (teacher sets the threshold), or Watch/listen the entire media (quiz unlocks only at the end). Students receive instant question-by-question feedback with a Try Again option.

Teachers configure maximum attempts, time limits, passing grades, and gradebook integration. Completion conditions can require achieving the passing grade. Credit cost: 5 credits per 150 words of transcript processed.';
$string['modulename_link'] = 'mod/aivideoactivity/view';
$string['pluginname'] = 'AI Video Activity';
$string['pluginadministration'] = 'AI Video Activity administration';
$string['videoactivityname'] = 'Name';

// Capabilities.
$string['aivideoactivity:addinstance'] = 'Add a new AI Video Activity';
$string['aivideoactivity:view'] = 'View AI Video Activity';
$string['aivideoactivity:create'] = 'Generate video quizzes with AI';
$string['aivideoactivity:viewreports'] = 'View AI Video Activity reports';
$string['aivideoactivity:manageoverrides'] = 'Manage attempt overrides';

// Settings.
$string['apiurl'] = 'API URL';
$string['apiurl_desc'] = 'The Essay Grader AI API URL. Default: https://lms-labs.com';
$string['siteid'] = 'Site ID';
$string['siteid_desc'] = 'Your Moodle site ID from lms-labs.com. This should match your registered site domain.';
$string['apikey'] = 'API Key';
$string['apikey_desc'] = 'Your API key from lms-labs.com. This is used to authenticate requests.';
$string['credits_heading'] = 'Credits';
$string['credits_info'] = 'AI Video Activity uses 5 credits per 150 words of transcript. Each question includes 4 options with AI voiceover explanations based on the video transcript. Purchase credits at <a href="https://lms-labs.com" target="_blank">lms-labs.com</a>.';

// Media type strings.
$string['mediasettings'] = 'Media Settings';
$string['mediatype'] = 'Media Type';
$string['mediatype_help'] = 'Choose whether to use a YouTube video or an audio file. Audio mode lets you upload spoken content like English speaking pieces, evacuation sirens, or podcast recordings.';
$string['mediatype_video'] = 'YouTube Video';
$string['mediatype_audio'] = 'Audio File';
$string['audiofile'] = 'Audio File';
$string['audiofile_help'] = 'Upload an audio file for students to listen to. Supported formats: MP3, WAV, OGG, M4A, AAC, FLAC, WMA, OPUS, WebM, AIFF. Maximum file size: 256MB.';
$string['audiofile_teacher_help'] = 'Audio files are managed via the activity settings page. Click "Edit settings" to upload or change the audio file.';
$string['audiourl'] = 'Audio File URL';
$string['audiourl_help'] = 'Enter a direct URL to an audio file (MP3, WAV, OGG, or M4A). You can upload audio files to your Moodle file area or use any publicly accessible URL.';
$string['audiourl_placeholder'] = 'https://example.com/audio/speaking-piece.mp3';
$string['audio_player_title'] = 'Audio Player';
$string['listen_requirement_msg'] = 'You must listen to the audio before attempting the quiz.';

// Video-specific strings.
$string['videosettings'] = 'Video Settings';
$string['youtubeurl'] = 'YouTube URL';
$string['youtubeurl_help'] = 'Enter the full YouTube URL for the video. The plugin will extract the transcript and use it to generate quiz questions.';
$string['youtubeurl_placeholder'] = 'https://www.youtube.com/watch?v=...';
$string['watchmode'] = 'Watch Requirement';
$string['watchmode_help'] = 'Set whether students must watch the video before attempting the quiz. "Watch entire video" requires full playback, "Watch minimum seconds" requires a set duration, and "No requirement" allows immediate quiz access.';
$string['watchmode_all'] = 'Watch entire video';
$string['watchmode_seconds'] = 'Watch minimum seconds';
$string['watchmode_none'] = 'No requirement';
$string['watchseconds'] = 'Minimum Watch Seconds';
$string['watchseconds_help'] = 'The minimum number of seconds students must watch before they can start the quiz. Only applies when watch mode is set to "Watch minimum seconds".';
$string['showvideoduringquiz'] = 'Show video above questions';
$string['showvideoduringquiz_help'] = 'When enabled, the video player remains visible above the quiz questions while the student is answering. This allows students to refer back to the video while responding. Only applies to video (not audio) activities.';
$string['showchapterstamps'] = 'Show chapter timestamp links';
$string['showchapterstamps_help'] = 'When enabled, each question displays a clickable timestamp link that jumps the video to the point in the transcript where the question topic is covered. Timestamps are automatically identified by the AI from YouTube-style timestamps in the transcript (e.g. "1:09"). Only applies to video activities.';
$string['transcript_label'] = 'Video Transcript';
$string['transcript_help'] = 'The transcript of the video. This is automatically fetched from YouTube when a valid URL is provided, but you can also paste or edit it manually. The AI uses this text to generate quiz questions.';
$string['transcript_placeholder'] = 'Paste or edit the video transcript here...';
$string['video_player_title'] = 'Video Player';
$string['watch_requirement_msg'] = 'You must watch the video before attempting the quiz.';
$string['watch_progress'] = 'Watch progress: {$a->watched} of {$a->required} seconds';

// Page content.
$string['page_title'] = 'AI Video Activity';
$string['page_heading'] = 'AI Video Activity';
$string['page_intro'] = 'Watch the video and complete the AI-generated quiz to test your understanding of the content.';
$string['credits_label'] = 'Credits Available';
$string['not_configured'] = 'Plugin not configured. Please set Site ID and API Key in the plugin settings.';
$string['students_view_message'] = 'This activity requires you to watch a video and complete a quiz. Check back later if the quiz has not been generated yet.';

// Attempt settings.
$string['attemptsettings'] = 'Attempt Settings';
$string['attemptlimit'] = 'Maximum attempts';
$string['attemptlimit_help'] = 'Set the maximum number of attempts allowed for this video activity quiz. Enter 0 to allow unlimited attempts.';
$string['unlimited'] = 'Unlimited';
$string['attempt'] = 'Attempt';
$string['attemptslimitreached'] = 'You have reached the attempt limit ({$a}).';

// CC Email notifications.
$string['ccemail'] = 'CC Email for Notifications';
$string['ccemail_help'] = 'Enter email addresses (comma-separated) to receive notifications when students reach their maximum attempts. This is in addition to teacher notifications.';

// Question generation.
$string['num_questions_label'] = 'Number of Questions';
$string['num_questions_help'] = 'Choose how many questions to generate from the video transcript. More questions provide better assessment coverage. Credit cost is based on transcript length (5 credits per 150 words).';
$string['generate_btn'] = 'Generate Quiz';
$string['generating'] = 'Generating Quiz...';
$string['quiz_ready'] = 'Quiz Ready!';

// Question type.
$string['question_type_label'] = 'Question Style';
$string['question_type_help'] = 'Choose the style of questions to generate. Application questions test understanding of concepts. Scenario questions present workplace situations for learners to analyse. Mixed generates half of each.';
$string['question_type_application'] = 'All Application of Knowledge';
$string['question_type_scenario'] = 'All Scenario-Based';
$string['question_type_mixed'] = 'Half Application / Half Scenario';

// Question format types.
$string['question_formats_label'] = 'Question Formats';
$string['question_formats_help'] = 'Select which question formats to include. The AI will distribute questions across your selected formats. At least one format must be selected.';
$string['format_mcq'] = 'Multiple Choice';
$string['format_mcq_desc'] = '4 options, pick the correct answer';
$string['format_cardselect'] = 'Card Select';
$string['format_cardselect_desc'] = 'Pick the correct concept card from visual options';
$string['format_matching'] = 'Matching';
$string['format_matching_desc'] = 'Match pairs of related items';
$string['format_ordering'] = 'Ordering';
$string['format_ordering_desc'] = 'Arrange items in the correct sequence';
$string['format_columnsort'] = 'Column Sort';
$string['format_columnsort_desc'] = 'Sort items into two categories (e.g. Good / Bad)';
$string['format_categorysort'] = 'Category Sort';
$string['format_categorysort_desc'] = 'Sort items into three or more categories';
$string['format_flashcards'] = 'Flashcards';
$string['format_flashcards_desc'] = 'Flip cards to review key concepts and definitions';
$string['format_truefalseswipe'] = 'True or False';
$string['format_truefalseswipe_desc'] = 'Swipe or tap to judge each statement as true or false';
$string['format_fillinblank'] = 'Fill in the Blank';
$string['format_fillinblank_desc'] = 'Complete a passage using words from a word bank';

// Scenario context.
$string['scenario_context_title'] = 'Scenario Context';
$string['scenario_context_help'] = 'Provide workplace context to make scenario questions realistic and relevant. The AI will create scenarios set in this country and industry.';
$string['scenario_country'] = 'Country';
$string['scenario_industry'] = 'Industry';
$string['scenario_subindustry'] = 'Sub-Industry / Specialisation';
$string['scenario_subindustry_placeholder'] = 'e.g. Aged Care, Mining Safety, Hospitality Management...';
$string['scenario_subindustry_help'] = 'Optional. Provide a more specific area within the industry to make scenarios more targeted and realistic.';
$string['select_option'] = '-- Select --';

// Voice settings.
$string['voiceover_enabled'] = 'Enable voiceover explanations';
$string['voiceover_enabled_help'] = 'When enabled, students hear spoken explanations after answering each question. Turn off to skip audio generation and speed up quiz creation.';
$string['voice_settings'] = 'Language & Voice Settings';
$string['voice_settings_help'] = 'Choose the language and voice for all question text and audio explanations. When students answer, they\'ll hear a spoken explanation of the correct answer.';
$string['voice_language'] = 'Language';
$string['language_help'] = 'Select the language for questions and voiceover explanations. All content will be generated in this language.';
$string['voice_gender'] = 'Voice Gender';
$string['voice_gender_help'] = 'Choose whether the AI narrator uses a male or female voice for the spoken explanations.';
$string['voice_female'] = 'Female';
$string['voice_male'] = 'Male';
$string['voice_style'] = 'Voice Style';
$string['voice_style_help'] = 'Choose a voice personality. Different styles suit different training contexts (e.g., professional for compliance, friendly for onboarding).';

// Languages - Complete Chirp 3 HD language list (51 languages).
// English variants.
$string['lang_en_au'] = 'English (Australia)';
$string['lang_en_gb'] = 'English (UK)';
$string['lang_en_in'] = 'English (India)';
$string['lang_en_us'] = 'English (US)';

// Spanish variants.
$string['lang_es_es'] = 'Spanish (Spain)';
$string['lang_es_us'] = 'Spanish (Latin America)';

// French variants.
$string['lang_fr_ca'] = 'French (Canada)';
$string['lang_fr_fr'] = 'French (France)';

// German.
$string['lang_de_de'] = 'German';

// Portuguese.
$string['lang_pt_br'] = 'Portuguese (Brazil)';

// Dutch variants.
$string['lang_nl_be'] = 'Dutch (Belgium)';
$string['lang_nl_nl'] = 'Dutch (Netherlands)';

// Nordic languages.
$string['lang_da_dk'] = 'Danish';
$string['lang_fi_fi'] = 'Finnish';
$string['lang_nb_no'] = 'Norwegian';
$string['lang_sv_se'] = 'Swedish';

// Eastern European languages.
$string['lang_bg_bg'] = 'Bulgarian';
$string['lang_cs_cz'] = 'Czech';
$string['lang_hr_hr'] = 'Croatian';
$string['lang_hu_hu'] = 'Hungarian';
$string['lang_pl_pl'] = 'Polish';
$string['lang_ro_ro'] = 'Romanian';
$string['lang_ru_ru'] = 'Russian';
$string['lang_sk_sk'] = 'Slovak';
$string['lang_sl_si'] = 'Slovenian';
$string['lang_sr_rs'] = 'Serbian';
$string['lang_uk_ua'] = 'Ukrainian';

// Baltic languages.
$string['lang_et_ee'] = 'Estonian';
$string['lang_lt_lt'] = 'Lithuanian';
$string['lang_lv_lv'] = 'Latvian';

// Southern European languages.
$string['lang_el_gr'] = 'Greek';
$string['lang_it_it'] = 'Italian';

// East Asian languages.
$string['lang_cmn_cn'] = 'Chinese (Mandarin)';
$string['lang_ja_jp'] = 'Japanese';
$string['lang_ko_kr'] = 'Korean';

// Southeast Asian languages.
$string['lang_id_id'] = 'Indonesian';
$string['lang_th_th'] = 'Thai';
$string['lang_vi_vn'] = 'Vietnamese';

// South Asian languages.
$string['lang_bn_in'] = 'Bengali';
$string['lang_gu_in'] = 'Gujarati';
$string['lang_hi_in'] = 'Hindi';
$string['lang_kn_in'] = 'Kannada';
$string['lang_ml_in'] = 'Malayalam';
$string['lang_mr_in'] = 'Marathi';
$string['lang_ta_in'] = 'Tamil';
$string['lang_te_in'] = 'Telugu';
$string['lang_ur_in'] = 'Urdu';

// Middle Eastern languages.
$string['lang_ar_xa'] = 'Arabic';
$string['lang_he_il'] = 'Hebrew';
$string['lang_tr_tr'] = 'Turkish';

// African languages.
$string['lang_sw_ke'] = 'Swahili (Kenya)';

// Voice styles (Chirp 3 HD).
$string['voice_aoede'] = 'Aoede (Warm)';
$string['voice_kore'] = 'Kore (Professional)';
$string['voice_leda'] = 'Leda (Clear)';
$string['voice_zephyr'] = 'Zephyr (Gentle)';
$string['voice_puck'] = 'Puck (Friendly)';
$string['voice_charon'] = 'Charon (Deep)';
$string['voice_fenrir'] = 'Fenrir (Strong)';
$string['voice_orus'] = 'Orus (Authoritative)';

// Quiz player.
$string['question_of'] = 'Question {$a->current} of {$a->total}';
$string['check_answer'] = 'Check Answer';
$string['next_question'] = 'Next Question';
$string['finish_quiz'] = 'Finish Quiz';
$string['correct'] = 'Correct!';
$string['incorrect'] = 'Incorrect';
$string['your_score'] = 'Your Score';
$string['questions_correct'] = '{$a->correct} of {$a->total} correct';
$string['play_explanation'] = 'Play Explanation';
$string['pause_explanation'] = 'Pause';

// Results.
$string['quiz_complete'] = 'Quiz Complete!';
$string['score_excellent'] = 'Excellent work!';
$string['score_good'] = 'Good job!';
$string['score_needs_improvement'] = 'Keep practising!';

// Reports and attempts.
$string['attemptsreport'] = 'Attempts Report';
$string['noattempts'] = 'No attempts yet.';
$string['username'] = 'User';
$string['attemptno'] = 'Attempt #';
$string['score'] = 'Score';
$string['timestarted'] = 'Time Started';
$string['timeended'] = 'Time Ended';
$string['timespent'] = 'Time Spent';
$string['inprogress'] = 'In Progress';
$string['review'] = 'Review';
$string['startquiz'] = 'Start Quiz';
$string['retakequiz'] = 'Retake Quiz';
$string['startnewattempt'] = 'Retake';
$string['backtocourse'] = 'Back to Course';

// More attempts management.
$string['moreattempts'] = 'More Attempts';
$string['moreattemptsheading'] = 'User Extra Attempts';
$string['userattempts'] = 'User Attempts';
$string['attemptsused'] = 'Attempts Used';
$string['attemptsallowed'] = 'Attempts Allowed';
$string['additionalattempts'] = 'Additional Attempts';
$string['totalallowed'] = 'Total Allowed';
$string['grantplusone'] = 'Grant +1';
$string['bulkgrantplusone'] = 'Grant +1 to Selected';
$string['view'] = 'View';
$string['actions'] = 'Actions';

// Notifications.
$string['messageprovider:allattemptsused'] = 'Notification when all attempts are used';
$string['allattemptsused_subject'] = 'All attempts used: {$a->activityname}';
$string['allattemptsused_body'] = 'User {$a->fullname} has used all {$a->limit} attempts for "{$a->activityname}" in the course "{$a->coursename}". Please review and, if appropriate, grant additional attempts at: {$a->overrideurl}';

// Completion.
$string['completionallcorrect'] = 'All answers must be correct';
$string['completionallcorrect_help'] = 'When enabled, the activity will only be marked as complete when the student answers all questions correctly in a single attempt.';
$string['completiondetail:completionallcorrect'] = 'Answer all questions correctly';
$string['completionpassgrade'] = 'Achieve passing grade';
$string['completionpassgrade_help'] = 'When enabled, the activity will be marked as complete when the student achieves the passing grade percentage set in the Grade settings section. Their best attempt score is used.';
$string['completiondetail:completionpassgrade'] = 'Achieve passing grade';

// Try Again.
$string['try_again'] = 'Try Again';

// Bloom's Taxonomy.
$string['bloom_level_label'] = 'Question Complexity';
$string['bloom_level_help'] = 'Set the thinking level of generated questions using Bloom\'s Taxonomy. Level 1 (Remember) asks simple recall. Level 3 (Apply) is the default and tests practical understanding. Level 6 (Create) demands the highest-order thinking.';
$string['bloom_level_1'] = 'Level 1 - Remember (recall facts and basic concepts)';
$string['bloom_level_2'] = 'Level 2 - Understand (explain ideas and concepts)';
$string['bloom_level_3'] = 'Level 3 - Apply (use information in new situations)';
$string['bloom_level_4'] = 'Level 4 - Analyse (draw connections among ideas)';
$string['bloom_level_5'] = 'Level 5 - Evaluate (justify a decision or course of action)';
$string['bloom_level_6'] = 'Level 6 - Create (produce new or original work)';

// AI Instructions.
$string['extra_instructions_label'] = 'AI Instructions';
$string['extra_instructions_placeholder'] = 'e.g. Focus questions on workplace safety procedures, use Australian English spelling...';
$string['extra_instructions_help'] = 'Optional. Add any custom instructions for the AI when generating questions, such as a focus area, terminology preferences, or additional context.';

// Errors.
$string['error_nocredits'] = 'Insufficient credits. Please purchase more credits at lms-labs.com.';
$string['error_generation'] = 'An error occurred while generating the quiz. Please try again.';
$string['error_invalid_session'] = 'Invalid session. Please refresh the page and try again.';
$string['error_no_transcript'] = 'No transcript available for this video. Please provide a transcript manually or try a different YouTube video.';
$string['error:negativeattempts'] = 'Maximum attempts cannot be negative.';
$string['error:invalidemail'] = 'Invalid email address format. Use comma-separated valid emails.';
$string['error:invalidgradepass'] = 'Grade to pass must be a valid number (0 or above).';
$string['error:gradepasstoohigh'] = 'Grade to pass cannot be higher than the maximum grade.';

// Grade settings.
$string['gradesettings'] = 'Grade settings';
$string['passinggrade'] = 'Grade to pass';
$string['passinggrade_help'] = 'Set the minimum grade a student must achieve to pass this video activity. Enter a number between 0 and the maximum grade (e.g. 80 when max grade is 100). This is used by the Moodle gradebook and completion conditions to show pass/fail status. Set to 0 to disable.';
$string['nopassinggrade'] = 'No passing grade';
$string['scoringmode'] = 'Scoring mode';
$string['scoringmode_help'] = 'Controls how student scores are calculated. "Retry until correct" lets students try each question again until they get it right — everyone finishes with 100% if they complete all questions. "First attempt only" locks the score after the first answer — wrong answers move the student forward without a retry, giving a score that reflects actual first-attempt accuracy.';
$string['scoringmode_retry'] = 'Retry until correct (default)';
$string['scoringmode_firstonly'] = 'First attempt only (score reflects accuracy)';

// Privacy.
$string['privacy:metadata:aivideoactivity_attempts'] = 'Information about user attempts on video activity quizzes.';
$string['privacy:metadata:aivideoactivity_attempts:userid'] = 'The ID of the user who made the attempt.';
$string['privacy:metadata:aivideoactivity_attempts:answers'] = 'The answers provided by the user.';
$string['privacy:metadata:aivideoactivity_attempts:timestarted'] = 'The time when the attempt was started.';
$string['privacy:metadata:aivideoactivity_attempts:timeended'] = 'The time when the attempt was completed.';
$string['privacy:metadata:essaygraderai'] = 'Video transcript data is sent to the Essay Grader AI service at lms-labs.com to generate quiz questions.';
$string['privacy:metadata:essaygraderai:transcriptdata'] = 'The video transcript text submitted for AI question generation.';

// Events.
$string['eventcoursemoduleviewed'] = 'Course module viewed';

// Activity list.
$string['novideoactivities'] = 'No AI Video Activity activities in this course.';

// Bulk Card Select audio upgrade (v1.0.114 — FEAT-VA-BULK-CARDSELECT-AUDIO-UPGRADE).
$string['bulkregen_heading'] = 'Bulk Card Select audio upgrade';
$string['bulkregen_info'] = 'Card Select questions created before v1.0.110 only have a single audio clip narrating the correct answer. To prevent spoiling the answer when a student picks a wrong card, those clips are silently suppressed on incorrect attempts. Run this one-click upgrade to walk every Card Select question across the whole site, regenerate four per-card voiceover clips (one for each card), and persist them back to the database. Existing question text is preserved — only the per-card explanations and audio are updated. After running, every existing Card Select question will play the correct per-card voiceover for the card the student actually picked, including on wrong answers, without giving the answer away.';
$string['bulkregen_link'] = 'Open bulk Card Select audio upgrade page';
$string['bulkregen_pagetitle'] = 'Bulk Card Select audio upgrade';
$string['bulkregen_count_button'] = 'Count legacy Card Select questions';
$string['bulkregen_run_button'] = 'Run upgrade now';
$string['bulkregen_running'] = 'Upgrading questions...';
$string['bulkregen_done'] = 'Upgrade complete.';
$string['bulkregen_intro'] = 'This page walks the entire site and upgrades every legacy Card Select question (those with only one audio clip) to the v1.0.110+ per-card audio format. Click "Count" first to see how many will be upgraded, then "Run" to start. The page processes one question per HTTP call so it will not time out, even on large sites.';
$string['bulkregen_no_legacy'] = 'No legacy Card Select questions found. All Card Select questions on this site already use per-card audio.';
$string['bulkregen_admin_only'] = 'Only site administrators may run this tool.';
